### ISSUE TITLE
Compatibility: Itron 40G (Gas ERT 02) and Itron 41ER-1 (Power ERT 05)

### ISSUE THREAD

**Issue by Legomaniac** [bemasher/rtlamr#105]
Hello, first I'd like to say thank you! This project has been a lot of fun, and by far the most inexpensive way to monitor consumption that I've come across! This isn't really an issue, just a request for insight, so I'm sorry if there is a more appropriate venue for my questions.

I have been using rtlamr over the last few days to collect data from my Neptune R900. I put in the ID number etched into the casing of my R900 as a -filterid argument and it's working flawlessly. I can watch the usage change and it corresponds directly to my actual usage. Awesome! 

However, I'm having difficultly finding my gas and electric meter in the output when I run with -msgtype=all

I read the labels, and my gas meter appears to be an ITRON 40G, while my electric meter appears to be an ITRON 41ER-1, both listed as compatible in the meters.csv file. However, I have run rtlamr for periods of about one hour, piped to a grep for either my electric meter ID, or my gas meter ID, and nothing is coming up... When I don't grep through the output, I am probably getting 3-5 readings a second, but none of them seem to correspond to the meter IDs of the meters actually attached to the house my NooElec NESDR Nano 2+ is sitting in...

The label on my electric meter is: 05 46373238
The label on my gas meter is: 02 27347157

From what I have read elsewhere, and it seems to correspond to the meters.csv file, the first two digits are the meter type, and the next 8 are the meter ID. So my greps have been for 46373238 and 27347157.

I just wanted to make sure I am not missing something here. Are these the IDs I should be looking for? Perhaps my utility has (before I moved in for example) replace the guts of the ITRON meter, but not updated the label? If so, does anyone know any techniques to help me identify which meter id is mine?

I am just trying to determine if I'm on the right path here. Sorry if there is a better place to ask such a question. And thanks again for contributing such an exciting project to the open source community.

**Comment by bemasher** [comment]
I also have a 40G. Unfortunately, I believe most of these are provisioned to run in wake-up mode, so they only transmit when the utility drives by and wakes them. They typically have sealed batteries intended to last the lifetime of the unit. You will likely only receive a message whenever the utility drives by to read them.

As for the power meter, I've not encountered any 05 type power meters in the wild. You might try listening with `-msgtype=scm,scm+,idm -filtertype=5` to see if your meter, or any others like it are transmitting regularly. You might also try a couple of different frequencies within the expected transmission bands. With an rtl-sdr radio, you can typically sample about 2.4 MHz at a time (with the default symbol length), so spacing the frequencies you try by that much should help you catch your meter if it's not using FHSS and only transmitting on one frequency outside of the default frequency.

The following commands should pick something up if your power meter is transmitting:
```bash
rtlamr -format=json -msgtype=scm,scm+,idm -filtertype=5 -duration=25m -centerfreq=911.1M > 911.1M.json
rtlamr -format=json -msgtype=scm,scm+,idm -filtertype=5 -duration=25m -centerfreq=913.4M > 913.4M.json
rtlamr -format=json -msgtype=scm,scm+,idm -filtertype=5 -duration=25m -centerfreq=915.7M > 915.7M.json
rtlamr -format=json -msgtype=scm,scm+,idm -filtertype=5 -duration=25m -centerfreq=918.0M > 918.0M.json
rtlamr -format=json -msgtype=scm,scm+,idm -filtertype=5 -duration=25m -centerfreq=920.3M > 920.3M.json
```
Stuff those into a batch file or bash script and let it run to completion, you should be able to find your meter in there if it is transmitting regularly. It is possible it is also configured to run in wake-up mode like your gas meter, though I hope that's not the case.

**Comment by Legomaniac** [comment]
Hey bemasher, thanks for the reply!

That's good to know about the gas meter. I was starting to wonder! 

As part of my troubleshooting process, I branched out from my Intel NUC home server where I was running everything, and installed the rtl-sdr/rtlamr stack on my Fedora laptop so I could walk around while scanning. Lo and behold, when I walked out into the garage and opened my garage door, I started to get readings from my electric meter (Did this before I saw your reply).

I purchased the following version of the NooElec from Amazon: http://a.co/d/bgeFNe2
The antenna that I have seen in several Youtube videos, where someone reported reading their electric meter through several brick walls, was more like this one: http://a.co/d/8HypnKb

I don't know enough about radio to know if it will make any difference (I'm an IT Software guy), but I bought it anyway because it was cheap and I got it free with points. It should be here tomorrow and I can test if it's any better than the telescoping one that came with the NooElec dongle.

I noticed on the configuration page that there are options for gain. However, I have a *very* cursory knowledge of radio, and have no idea what reasonable values are for the various options, or if changing them would even help receive my power meter's output from where my NUC sits. Is this something I could try adjusting? If so, where would you recommend I start?

My house was built in late 2003, and what triggered my whole investigation into this was a letter I received from my city to schedule an appointment to replace my water meter. After it was replaced, I went down in the crawlspace to see what they had installed and got to Googling, and that's what brought me here. I am hoping this might mean that my Gas/Electric utility may upgrade my existing meters soon as well. However, I'd love to get as many readings as possible from my current meters, especially if they intend to leave the existing ones in place for more years of service.

Thanks again, you have a really awesome project on your hands here!

**Comment by bemasher** [comment]
You probably shouldn't need to adjust the default gain settings, or get any specialized antennas to read meters attached to your own home. The only time that may be problematic is if your home has a lot of metal in the walls, or they're unusually thick.

A common approach is to use a low-power single board computer like the Raspberry Pi to listen to your meters, and then handle storage and processing on another more powerful system. Your RPi can be placed closer to your meters if that is necessary for it to receive them, however it may not be powerful enough to receive more than one message type at a time.

**Comment by Legomaniac** [comment]
Thanks again for responding! I actually hadn't had the chance to make a bash script with your suggestions until this morning as I've been busy with friends in town. 

When I got back to my NUC, I pasted your suggestions into a file, and let it run as I was out. I also added in one for default, where I left the centerfreq argument off entirely. Here were the results when I arrived:

[legomaniac@diginuc bin]# grep -c 46373238 *.json
911.1M.json:0
913.4M.json:151
915.7M.json:974
918.0M.json:558
920.3M.json:0
default.json:0

It looks like this is fine with my r900 as well, as when I run in single mode with both IDs at that frequency, it only takes 2 or 3 seconds to run and spit out both my water and electric consumption. Hooray! This is exactly what I was hoping for!!

I suppose my only remaining question is if you've successfully read your 40G when the utility has woken it up, and if so, do you think a center frequency of 915.7 megahertz would do the trick? 

Thanks again for your help, and I hope this data is useful for you!

**Comment by bemasher** [comment]
I haven't attempted to leave a receiver running long enough with settings to listen to my gas meter. Consumption readings every 30ish days doesn't really do me much good so I don't have much incentive to do it.

Listening on 915.7 MHz would probably do what you need so long as the message type is SCM.
