### ISSUE TITLE
Landis Gyr+ E470

### ISSUE THREAD

**Issue by bachoo786** [bemasher/rtlamr#106]
Hi all

Does this software work with Landis Gyr+ E470? Apparently the smart meter uses zigbee but I am not sure. 

thanks.

**Comment by bemasher** [comment]
To my knowledge, the only Landis+Gyr supported meters are all from the Airpoint series. If your meter uses zigbee, rtlamr cannot receive it's messages.

**Comment by bemasher** [comment]
For the curious among you, this page has quite a lot of good information regarding Landis+Gyr meters and decoding the protocol at least some of them use.

https://wiki.recessim.com/view/Gr-smart_meters_Setup_Guide
