### ISSUE TITLE
New 'Aclara' meter replaces Itron - no messages

### ISSUE THREAD

**Issue by burrowmoor** [bemasher/rtlamr#108]
Hi - I'd be very grateful for your quick comment on the attached pic of a new AEP installation which replaces a working Itron/rtlamr setup. Am I right in concluding from the Silver Springs I-210+c FCC data that the new meter has both 915MHz and 2.4GHz radios installed? Can you tell me why the rtlamr setup no longer successfully delivers data sentences the way the previous Itron one did on 915MHz - are they encrypting the data or expecting a stimulus I'm not providing? Does the fact that the meter ID has hexadecimal characters mean it's an OpenWay device? Is it using FSK? My familiarity with all this has faded, so anything you can tell me will be welcomed!
![aep new meter](https://user-images.githubusercontent.com/25270620/49545194-ed0d4a00-f8aa-11e8-8312-2a9ea77e222e.jpg)

**Comment by bemasher** [comment]
Silver Spring Networks NICs have their own proprietary protocol which I've not had any experience with. Unfortunately these are not supported by rtlamr.
