### ISSUE TITLE
CenterFreq is not changing from default 912380000

### ISSUE THREAD

**Issue by gbdavidx** [bemasher/rtlamr#112]
https://imgur.com/a/nHqmdME after using the flag to change it, -centerfreq=462, it still shows 912 ect...

**Comment by bemasher** [comment]
Unfortunately adding multi-protocol support has broken some of the displayed values, it is still setting the center frequency correctly, it's just not displaying it on startup.

**Comment by gbdavidx** [comment]
so this is a bug even though it's been added as a feature?

**Comment by bemasher** [comment]
It became a bug when stopped behaving like it should. It still works underneath, it just isn't displaying the correct value.
