### ISSUE TITLE
Docker rtlamr error - $PATH": unknown

### ISSUE THREAD

**Issue by b-rockx** [bemasher/rtlamr#117]
When running the command to build the docker after rtltcp is running. 

`docker run -d --name rtlamr --link rtltcp:rtltcp bemasher/rtlamr -server=rtltcp:1234`

I receive the error 
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"-server=rtltcp:1234docker\": executable file not found in $PATH": unknown.
`

**Comment by mdonoughe** [comment]
You need to have rtlamr before the parameter name, like `docker run -d --name rtlamr --link rtltcp:rtltcp bemasher/rtlamr rtlamr -server=rtltcp:1234`

**Comment by b-rockx** [comment]
The docker line above worked. Thanks
