### ISSUE TITLE
Itron 50w

### ISSUE THREAD

**Issue by gomer23** [bemasher/rtlamr#118]
Hello, I set up rtlamr yesterday and have been able to pull SCM from my gas and electric meter. But the itron 50w that is on my water meter doesn't seem to be showing up. I see that meter is on the supported list. I have the nooelec USB device from Amazon for reading the data and using a RPi3. Is there a different frequency or setting I need to change to pick up the messages from the 50w?

**Comment by bemasher** [comment]
Battery-operated meters like the 50W are frequently operated in wake-up mode, which means they don't transmit unless woken up by the utility's transmitter. You might also check to see if it is transmitting SCM+.

**Comment by gomer23** [comment]
That makes sense and I did check SCM+. It looks like newer models are doing SCM+ but it's sounding like it's in wakeup mode. Time to look at other options I suppose.

**Comment by greyltc** [comment]
I have this meter too. Any idea how to trigger the wakeup?
