### ISSUE TITLE
Typo in example Environment variables

### ISSUE THREAD

**Issue by demiller9** [bemasher/rtlamr#119]
I cut and pasted to create an environment variable but it didn't work. Turns out the flag name is misspelled.
RLTAMR_MSGTYPE=idm (should be RTLAMR_MSGTYPE=idm)

**Comment by bemasher** [comment]
Thanks for the help. Fixed in [7e4f27d](https://github.com/bemasher/rtlamr/wiki/Configuration/7e4f27d5cfb213fb6f358ac7167b938f59f47295).
