### ISSUE TITLE
Zigbee SE Profile?

### ISSUE THREAD

**Issue by spynn56** [bemasher/rtlamr#121]
Hey! I believe that my meter is using Zigbee Smart Energy Profile to create a mesh network to transmit the data. Are the messages that you are pulling here raw Zigbee data? Just wondering if I should begin to look into the RTL-SDR if it cannot read the Zigbee messages.

Setup for Reference:
Meter: Landys+Gyr FOCUS kWh ALF FM 2S  https://www.solar-electric.com/lib/wind-sun/Focus-technical-manual.pdf
Module: Trilliant Networks NCZR101PH w/Zigbee https://fccid.io/TMB-EM000018/Test-Report/Test-Report-750167

**Comment by bemasher** [comment]
Typically rtl-sdr radios are only capable of receiving between 50MHz and 1.7GHz, that test report shows the device operates in the 2.4GHz ISM band.
