### ISSUE TITLE
rtl_tcp and rtlamr in different RPi(s)

### ISSUE THREAD

**Issue by uriva9w** [bemasher/rtlamr#132]
Hi All
I want to understand
"If you want to run the spectrum server on a different machine than the receiver you'll want to specify an address to listen on that is accessible from the machine rtlamr will run on with the -a option for rtl_tcp with an address accessible by the system running the receiver."

I want to run rtl_tcp in one RPi (A)...and rtlamr in another RPi (B)
Could you please give me un example?
In (A): rtl_tpc -a 192.168.1.1
What about (B)?

Thank you very much

**Comment by bemasher** [comment]
If RPi (A) is running `rtl_tcp -a 192.168.1.1`, then
on RPi (B) you would then use `rtlamr -server=192.168.1.1:1234`
