### ISSUE TITLE
Using with other SDR radios 

### ISSUE THREAD

**Issue by noneck35** [bemasher/rtlamr#133]
Is there compatibility with SDRPlay or Hack RF one? Do I need to have RTL-SDR?

Thanks for the help!

**Comment by parkerlreed** [comment]
This may help https://www.rtl-sdr.com/rsp_tcp-an-rtl_tcp-compatible-iq-server-for-sdrplay-sdrs/

https://www.reddit.com/r/RTLSDR/comments/1rd3wn/beta_hackrf_tcp_quick_port_of_rtl_tcp_for_hackrf/

**Comment by noneck35** [comment]
Thank you very much for this information
Mark

    On Wednesday, December 4, 2019, 1:02:23 PM PST, parkerlreed <notifications@github.com> wrote:  
 
 
This may help https://www.rtl-sdr.com/rsp_tcp-an-rtl_tcp-compatible-iq-server-for-sdrplay-sdrs/

https://www.reddit.com/r/RTLSDR/comments/1rd3wn/beta_hackrf_tcp_quick_port_of_rtl_tcp_for_hackrf/

**Comment by bemasher** [comment]
Rtlamr is designed with rtl-flavored radios in mind. That doesn't mean it couldn't be made to work with other radios, but I don't have time or hardware to support radios other than rtl-sdr's. There are a few mechanisms that are limited such that only rtl-sdr's would work, but they can be easily modified or disabled.

This would be left as an exercise for the user.
