### ISSUE TITLE
Frequency Hopping

### ISSUE THREAD

**Issue by sjd227** [bemasher/rtlamr#144]
Hello,

It seems that the ERT protocol uses frequency hopping, which I discovered in the [ERT wikipedia article](https://en.wikipedia.org/wiki/Encoder_receiver_transmitter) as well as some datasheets of meters I'm trying to pick up. But it doesn't look like frequency hopping is implemented in this project. Is it not required when using an rtl-sdr dongle - e.g., because the dongles can search for the signals within a large bandwidth at once? 

I saw #86 but I'm curious what the requirements are to not need to do frequency hopping. Is there any kind of special demodulation done in this project, that's specific to an rtl-sdr dongle, or can the built-in demodulation on chips such as the [sx1272](https://www.semtech.com/products/wireless-rf/lora-transceivers/sx1272) be used to pick up messages over a broad spectrum? If so are there specific requirements on e.g., bandwidth?

Thanks,
Steven

**Comment by bemasher** [comment]
Some meters transmit on a fixed frequency, some use frequency hopping. The protocol is amplitude modulated which means it is frequency agnostic, so long as the message is transmitted within the receivable bandwidth of an rtl-sdr dongle (up to 2.4 MHz), rtlamr will decode it.

One issue with doing it this way is that messages transmitted simultaneously on different frequencies will usually corrupt each other, or only the highest power message will be decoded. If you have a particular meter you want to hop along with it's not unreasonable to discover the hopping pattern and sync up with it. However it adds unnecessary complexity so it is not implemented in rtlamr.

You could definitely use an SX1272 to receive messages from these meters, they are relatively narrow band so you will only really be able to listen to a single channel at a time.
