### ISSUE TITLE
Help figuring out what I'm looking at

### ISSUE THREAD

**Issue by mconlow** [bemasher/rtlamr#145]
Hi, Would love any help figuring out what I'm looking at. My antenna is pulling in readings like this: https://ibb.co/kG4MMHc

As far as I can tell, neither my gas, power, or water meter should be readable. I have a Itron 40G gas meter which I've read here is a wake-up meter. My power meter is a Focus AXR-SD which I've read here isn't supported, and the water meter is a STAR 3321-012-DBW which looks to be on a different frequency. None of the ID numbers in any of the places on any of these meters is an ID number coming across in this screen shot. 

Any idea what meters I could possibly be picking up?

Thanks for the help

**Comment by bemasher** [comment]
Endpoint type 12 typically corresponds to gas. Your meter may be 40G but others in your neighborhood may have been upgraded to 60G or 100G's which usually transmit in bubble-up mode. Your meter could also be configured for bubble-up mode. I can help you identify your meter's endpoint ID if you'd like to send me some photos of your meter privately.
