### ISSUE TITLE
No data packets being received (I think?)

### ISSUE THREAD

**Issue by dreday99** [bemasher/rtlamr#147]
Hi, I am going to apologize beforehand, as I am pretty inexperienced with source coding and coding in general.  I believe I am running all the steps correctly, however, I don't seem to be receiving any data on my RTLAMR terminal window.  I am running OS X 10.13.6.  My water meter is a SENSUS iPERL.  Here are all the steps as well as the command results:

1. First I run rtl_tcp in terminal window 1:
![image](https://user-images.githubusercontent.com/64139552/79977708-b36fbb80-846c-11ea-9706-05b0f60655de.png)

2. Next, I open a second terminal window and run rtlamr:
![image](https://user-images.githubusercontent.com/64139552/79977762-c6828b80-846c-11ea-838b-74d7ad8cc463.png)

3. This is what the rtl_tcp window looks like once I run RTLAMR:
![image](https://user-images.githubusercontent.com/64139552/79977810-d9955b80-846c-11ea-99b1-2f24167edaf0.png)

I have had rtlamr run for about 24h and nothing ever popped up on my rtlamr terminal in terms of data packets.  Is there anything I am doing noticeably wrong?  Thank you

**Comment by dreday99** [comment]
I want to point out that the blank spaces in the code above was just me removing my last name from the line.  Thanks.

**Comment by bemasher** [comment]
Sensus meters are generally not supported. You're not seeing messages because your meter likely uses a protocol other than ERT.

**Comment by dreday99** [comment]
Is there any way to support it or is this a complete dead end for me?

Thanks again.

**Comment by bemasher** [comment]
Sensus is quite tight-lipped about their protocol and documentation for it, without physical access to a provisioned meter, it would be more difficult to reverse-engineer than I have time or resources for. Sorry.
