### ISSUE TITLE
Additional info for meters.csv

### ISSUE THREAD

**Issue by scott2449** [bemasher/rtlamr#149]
In trying to figure out my own meter I found this doc https://usermanual.wiki/Document/GridInsightOV1IntegrationGuide2020093202020160512.2094274720/view 

page 9 container ranges and fcc ids that are not in your csv. Would like me to make a PR?

**Comment by bemasher** [comment]
That'd be great! Just mention this issue # in the pull request.

**Comment by bemasher** [comment]
Closed due to inactivity.
