### ISSUE TITLE
How Do I Verify My Meter is Compatible?

### ISSUE THREAD

**Issue by dima-ser** [bemasher/rtlamr#150]
I'd like to be able to read my power readings, but my power meter is not listed in the compatible list. I have this meter: https://sensus.com/products/stratus/ and this FCC ID: http://fcc.io/SDBIDTB004

It does seem to operate in 900MHz range, but before I buy the radio receiver dongle, I want to make sure it will work. Or at least, how to I verify it works when I buy it, I'm new to the whole radio thing.

**Comment by bemasher** [comment]
Unfortunately Sensus meters are not supported.
