### ISSUE TITLE
docs: Identifying a Meter

### ISSUE THREAD

**Issue by skullydazed** [bemasher/rtlamr#153]
I don't know how universally true this is, but I found that my particular meter was easy to identify once I noticed that the ID is printed just above the KWH display. I think this would be useful information to include in the Ethics section of the readme.

![IMG_0415](https://user-images.githubusercontent.com/9553982/84414317-a9458000-abc6-11ea-9096-89b5c61126eb.jpg)

Output from rtlamr:

```
{Time:2020-06-11T16:04:13.198 SCM:{ID:20769XXX Type: 7 Tamper:{Phy:00 Enc:00} Consumption:  637838 CRC:0x4A40}}
```

**Comment by bemasher** [comment]
There are a bunch of meter photos available in fcc test reports, I'll compile some examples.

**Comment by mmiller7** [comment]
I'll add this may vary a lot by meter type, in my case (Dominion Energy analog meter) the ID on the front of the dial is wrong, the correct ID to look for is on a label affixed to the RF module under/behind the dial visible thru the bottom of the glass.

`{Time:2021-07-18T12:26:33.198 SCM:{ID:48722275 Type: 5 Tamper:{Phy:03 Enc:03} Consumption: 2127374 CRC:0xB011}}`

![image](https://user-images.githubusercontent.com/606945/126074825-fb983068-9bb1-4655-8219-7a93f6769f13.png)
