### ISSUE TITLE
Compatability: Landis+Gyr Power + Gas Meters

### ISSUE THREAD

**Issue by DigWorm0** [bemasher/rtlamr#154]
### FCC:
[Gas Meter](https://fccid.io/R7PGRAMCNLX1)
[Power Meter](https://fccid.io/R7PEG1R1S2)

I'm pretty sure the power meter is incompatible because it operates on a mesh network, but the gas meter says it should operate on 917.58 MHz according to the FCC. Yet, nothing appears to be transmitting on that frequency.

**Comment by bemasher** [comment]
Unfortunately, neither of these meters are supported.

**Comment by bemasher** [comment]
For the curious among you, this page has quite a lot of good information regarding Landis+Gyr meters and decoding the protocol at least some of them use.

https://wiki.recessim.com/view/Gr-smart_meters_Setup_Guide
