### ISSUE TITLE
Research information

### ISSUE THREAD

**Issue by hllhll** [bemasher/rtlamr#175]
Hello,
Here we have a similar product, I guess. it uses 433 ISM band, with some form of FHSS and a 4fsk or c4fm or CPSM 4 whatever you'll call it. Also i've found links between the company issued the tech here, and iTron.
[HackAday specifies](https://hackaday.com/2014/02/25/using-sdr-to-read-your-smart-meter/) that there's some paper explaining how you researched everything, but it's 404.

1. Is there any chance it would just work?
2. where can I find the paper/research information/how did you solved the tens of different issues that it takes.

Personally, I've spend weeks trying just to decode a short 4fsk burst, only to realise it's combined within a wider burst pattern and I've succumbed to my fatigue trying solve this project. 
The meter can be triggered to send data with a magnet somewhere along the meter (water meter). 

In my numerous hours trying to research this, I've got to [this device](https://fccid.io/ANATEL/01493-15-03592/), that seem from an rf perspective to be almost exactly the same. (No, my country doesn't have any public filings/documentation regarding rf stuff in the country)

**Comment by bemasher** [comment]
There's no chance that could "just work" with rtlamr. ERT is a manchester coded OOK signal.

**Comment by hllhll** [comment]
And about the title of the question, what about (2)? Do you have some documentation/thought process how you got to this implementation and/or, how do you  track fhss?

**Comment by bemasher** [comment]
Rtlamr doesn't track with the meter when it hops channels. Except for IDM packets, the data transmitted doesn't update with every hop anyway, so it's good enough to listen to about 12 contiguous channels. IDM packets only update a time field every transmission.

Luckily, ERT's modulation and coding make it very straight forward to demodulate and decode messages, even very weak signals when listening to a relatively wide portion of the band they are transmitted in.
