### ISSUE TITLE
SK9AMI-4 meter is OpenWay?

### ISSUE THREAD

**Issue by utdrmac** [bemasher/rtlamr#179]
CSV says supported via rtlamr:
https://github.com/bemasher/rtlamr/blob/master/meters.csv#L21

But your comment on this post indicates that is not correct since this unit uses OpenWay/ZigBee
https://www.gitmemory.com/issue/bemasher/rtlamr/122/526968887

**Comment by bemasher** [comment]
The meter's transmitter is ERT-capable, but may not be provisioned to use ERT.

**Comment by utdrmac** [comment]
I've worked my way from `~/go/bin/rtlamr -msgtype=all -centerfreq=902M` to `928M`. If I never received a reply from elec meter, safe to assume it is not using ERT?
