### ISSUE TITLE
SK9ACT2 Support

### ISSUE THREAD

**Issue by arduino43** [bemasher/rtlamr#190]
I believe this is an unsupported meter but wanted to check.

SK9ACT2
https://www.nspower.ca/images/default-source/default-album/d1-meter.jpg?sfvrsn=f3fd6b2c_1

Thanks!

**Comment by bemasher** [comment]
You are correct, that meter looks like some flavor of OpenWay.

**Comment by arduino43** [comment]
> You are correct, that meter looks like some flavor of OpenWay.

Thanks for the quick reply
