### ISSUE TITLE
Signal Strength

### ISSUE THREAD

**Issue by mmiller7** [bemasher/rtlamr#203]
Is there an option that I'm not seeing to have signal strength (RSSI, SNR, anything) dumped for each record?

I'd like to be able to compare different antennas and locations to see the best to use but I can't find any way to figure out how "good" the signal is that its decoding.

**Comment by bemasher** [comment]
Getting "real" values for RSSI or measuring SNR is relatively complicated and not included in rtlamr. I would gauge signal strength based on the number of received messages over time.

You can also use `-samplefile` and manually inspect received messages relative to the noise floor.
