### ISSUE TITLE
SoapySDR

### ISSUE THREAD

**Issue by bluegizmo83** [bemasher/rtlamr#209]
I saw a closed issue tracker from two years ago about possibly adding support for SoapySDR Remote streams. Is that something that's still a possibility? I'd love to be able to use devices other than RTLSDR sticks.

**Comment by bemasher** [comment]
SoapySDR Remote's protocol is non-trivial to implement and I'm not aware of any existing implementations in Go. I had started some work on this, but I don't have much time or need for this feature.

Some design requirements for rtlamr also limit the kinds of radios you could use with it, for example, only signed 8-bit samples are currently supported.
