### ISSUE TITLE
Update "Requirements" in README.md

### ISSUE THREAD

**Issue by mwaterbu** [bemasher/rtlamr#212]
60f79de41d8e3519b9aec9ddf7d34ba133d99178 added "context" as an import for main.go
This changes the GoLang requirement to >=1.7, as context was added as a standard library in 1.7 (https://golang.org/doc/go1.7#context).
Prior to this it would need to be imported as "golang.org/x/net/context", making versions prior to 1.7 throw errors during installation.

**Comment by bemasher** [comment]
Turns out the minimum version is 1.11 from use of go modules. I believe it can be made to function down to 1.7, but I'm not sure it's worth the effort.

Updated readme to reflect correct minimum version.
