### ISSUE TITLE
package github.com/bemasher/rtlamr@latest: can only use path@version syntax with 'go get'

### ISSUE THREAD

**Issue by enkrypt3d** [bemasher/rtlamr#221]
```
root@raspberrypi:~# go install github.com/bemasher/rtlamr@latest
package github.com/bemasher/rtlamr@latest: can only use path@version syntax with 'go get'
```

I have tried putting export GO111MODULE=on in my .bashrc with no luck........

**Comment by bemasher** [comment]
What is the output of `go version`?

**Comment by enkrypt3d** [comment]
***@***.***:~ $ go version
go version go1.15.9 linux/arm

I got it working with the older version.... still trying to get my Itron
B172 gas meter to show up. no luck so far.

**Comment by bemasher** [comment]
Per the readme, you need to use

```bash
go get github.com/bemasher/rtlamr
```

in versions prior to 1.16
