### ISSUE TITLE
Add support for Network Interval Message (NIM) format

### ISSUE THREAD

**Issue by dcarter** [bemasher/rtlamr#23]
I have the Itron gas meter described in the link below. I don't know for certain if my utility has implemented the Fixed Network Mode or not, but it it has, it would be very useful to get access to the hourly data from the NIM message format. It is interesting to note that the NIM is FM-modulated, while all the other messages are AM. 

https://www.itron.com/PublishedContent/100G%20Datalogging%20FN%20ERT%20Module%20Specifcation%20Sheet_100941SP-09.pdf

NIM message details: 
https://www.itron.com/PublishedContent/Water%20AMI%20100W%20Network%20Interval%20Message.pdf

**Comment by bemasher** [comment]
The basic structure of NIM messages is very similar to IDM however I have yet to discover the checksum used if it is different from IDM possibly because I have no meters in my area transmitting NIM's.

**Comment by bemasher** [comment]
If you can provide signal captures of several NIM messages, I can move ahead with this. I have another person requesting support for this, but I haven't yet found any NIM messages in the various samples they've provided.

**Comment by bemasher** [comment]
Further investigation has shown that NIM messages are FSK only and use a different preamble I've yet to find any good samples of in the wild.

I've also looked at various ways to implement this that maintain the ability to receive messages over the entire bandwidth of the receiver but none of these fit within the performance requirements without specialized non-portable code.

In the future I may fork this project to write RPi optimized version and multi-channel FSK decoding may be a possibility. Until then, without verified samples or hardware to test with, it's not something I'm up to implementing.
