### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by dcarter** [bemasher/rtlamr#24]
I'm running on OS X, and find that rtlamr will only run for a few minutes before either freezing up, or exiting with a "connection reset by peer" message. Both processes are on the same machine. 

I started down the path of creating a watchdog script to kill & restart both rtl_tcp & rtlamr if no log entries written in some number of minutes, but thought there might be a better approach. 

Is it possible that my sample rate needs to be lowered? 

Or is there a way to modify the error handling in recv.go to retry after receiving this error from the call to rcvr.Read()? 

Seems that it would be simplified if rtlamr used libsdr directly rather than in a separate process, but I'm a complete Go beginner, and don't really understand the motivation behind this design decision.

**Comment by bemasher** [comment]
The fix only *allows* cross-compilation with cgo in use, it doesn't mean that it will succeed for all platforms. Adding an external build dependency is just not something I'm prepared to deal with or support.

**Comment by dcarter** [comment]
On the MacBook that is configured to never sleep, the 2 processes have run without error now for about 3 days. I did find this error message on the MacBook where I originally had this set up. I don't know for a fact, but I think this error probably occurred when the system went to sleep or when it woke back up. 

18:53:10.433463 recv.go:133: Error reading samples: read tcp 127.0.0.1:1234: connection reset by peer

Would it be reasonable to add a retry loop in this particular error situation? Perhaps with a retry count command line parameter.

**Comment by bemasher** [comment]
Unfortunately, I believe this particular error is unrecoverable without rtlamr controlling instantiation of rtl_tcp which I would like to avoid.

I don't know what the OS X equivalent to this would be but using systemd to instantiate the services and to automatically restart them upon failure would work nicely. I believe OS X's closest solution is launchd, so you might look into that.
