### ISSUE TITLE
Arad / Master Meter water utility meter

### ISSUE THREAD

**Issue by avicarmeli** [bemasher/rtlamr#244]
I am trying to add a decoder for Arad/Master Meter water utility meter to rtl433 with some success. I was able to read meter's serial number and water counter as I posted [here](https://reverseengineering.stackexchange.com/questions/30133/reverse-engineering-a-weird-32-bit-possibly-not-crc-checksum). 
I wonder, maybe with your experience with other meters you can help decoding the rest of the massage?

**Comment by bemasher** [comment]
From your captures, can you tell me what the modulation is?

**Comment by avicarmeli** [comment]
It is Manchester NRZ IEEE.

**Comment by bemasher** [comment]
Hmm, can you provide some sample captures?

**Comment by avicarmeli** [comment]
Do you mean other than what I posted [here](https://reverseengineering.stackexchange.com/questions/30133/reverse-engineering-a-weird-32-bit-possibly-not-crc-checksum).?

**Comment by bemasher** [comment]
I mean IQ data, if possible.

**Comment by avicarmeli** [comment]
You can find [here ](https://drive.google.com/drive/folders/1o2rRn8eZM9zINk7zcZ138HbxPmDh7y2G?usp=sharing)some data.

**Comment by nickrobinson** [comment]
@avicarmeli Were you able to make any progress here? I'm working through trying to get data from a Master Meter and am trying to replicate some of your work here.

**Comment by avicarmeli** [comment]
@nickrobinson you can take a look at what I have by now  [here](https://github.com/avicarmeli/rtl_433).
It is still a work in progress.

**Comment by Mindful** [comment]
@avicarmeli Are you still working on this? 
I've suddenly become very interested in being able to read my (Master Meter) water meter.

**Comment by avicarmeli** [comment]
Hi Josh

I ended up just compiling very limited version of the driver since I can only read the water consumption and could not decode the rest of the massage.

It works fine for me to read the water counter.


If need any specific help don't hesitate to write me.


Avi

**Comment by avicarmeli** [comment]
One more thing is that I might made the preamble longer in order to read only my meter , so in that [file](https://github.com/avicarmeli/rtl_433/blob/master/src/devices/arad_ms_meter.c) you might want to change line 48 to shorter preamble or to one which comply to your 's meter serial number.

**Comment by Mindful** [comment]
@avicarmeli This makes sense - ultimately if I can read consumption that will be enough for me as well, so I think I'm just going to have to buy a dongle and play around with it. Thanks for your work on this!

I'll let you know how it goes, although that will probably be at least a few weeks out.

**Comment by bemasher** [comment]
See #284
