### ISSUE TITLE
Data output to xively.com for graphing

### ISSUE THREAD

**Issue by jgarland79** [bemasher/rtlamr#25]
Feature request:

Push data to xively.com using the meter serial number as the device id to generate graphs.

**Comment by bemasher** [comment]
This project is ultimately concerned with receiving and outputting messages in a useful format, it is up to the user to handle the data, that includes integration with external services.

**Comment by sandeen** [comment]
It should be trivial to just wrap a shell script around rtlamr in one-shot mode with csv output, then parse & upload data to xively using curl.  Run it every 15 minutes or so in cron, and you're done.
