### ISSUE TITLE
Compatibility: OWS-NIC514

### ISSUE THREAD

**Issue by rabarar** [bemasher/rtlamr#254]
Should this meter work with the FCC-ID below - and if so, how should I configure it.

https://fccid.io/OWS-NIC514

**Comment by bemasher** [comment]
Silver Spring Networks radios aren't supported.

https://github.com/bemasher/rtlamr/issues/108
https://github.com/bemasher/rtlamr/issues/151
https://github.com/bemasher/rtlamr/issues/157

**Comment by rabarar** [comment]
Thanks Doug!
