### ISSUE TITLE
Not receiving IDM messages

### ISSUE THREAD

**Issue by bmccoy11** [bemasher/rtlamr#26]
I'm receiving lots of SCM messages from 3 different CellNet meters, but I haven't picked up 1 IDM message after running rtlamr for hours with -msgtype=idm. Do some meters not send IDM messages?

**Comment by bemasher** [comment]
Not all meters are configured to send IDM messages. Some meters are also not capable of sending IDM messages. If you have a capture from your dongle of what you believe are IDM messages I'd be willing to take a look at it and help you determine if they are in fact IDM messages.
