### ISSUE TITLE
scm+

### ISSUE THREAD

**Issue by vonPalm** [bemasher/rtlamr#260]
Newbie here to coding/go and AMR reading.

I have had success in working with SCM meters (Itron 100G DLT) but not with SCM+ (Itron 100G DLS).  I know rtlamr has the scm+ capabilities but how do I configure the tool to read this message type vs. scm at command prompt launch?

**Comment by mdshw5** [comment]
See the section in the wiki on configuring message types: https://github.com/bemasher/rtlamr/wiki/Multi-Protocol-Decoding. You'll want to do something like `rtlamr -msgtype=scm+`.
