### ISSUE TITLE
Integrating American Meter Company model AC-250 Gas Meter 

### ISSUE THREAD

**Issue by amdjml** [bemasher/rtlamr#266]
Hi all,

I've been using the [rtlamr2mqtt](https://github.com/allangood/rtlamr2mqtt) project to monitor my electricity. It's working well. This led me to try to integrate my gas meter consumption into HA as well, however, I am unable to locate my meter when running the add-on in docker using the DEBUG MODE.

My gas meter is model AC-250 from American Meter Company. Hope someone here can assist me on making this work if it possible.

![IMG_0162](https://user-images.githubusercontent.com/875782/200011178-04407070-757b-4b50-a10f-ef4abaf6838d.JPG)

**Comment by moasson** [comment]
Ah, ok. So, I should still be able to pick it up if I keep the scan running with the meter ID? What would be the meter ID here? Is it the number on the meter itself or the meter number showing up in my gas bill?

**Comment by bemasher** [comment]
See #284.
