### ISSUE TITLE
ITRON 40G - Unable to find meter or no messages?

### ISSUE THREAD

**Issue by sofakng** [bemasher/rtlamr#268]
I'm trying to read messages from my gas meter that has the following sticker:
![image](https://user-images.githubusercontent.com/2228499/202297415-8e981a87-f94c-450a-a435-d2bc7c7ac40a.png)

It appears to be an ITRON 40G which after researching I understand could be configured in wake-up mode instead of bubble mode so I would only see messages once month, etc.  There is a number on the ITRON label that I've redacted because I'm not sure if it's my account number or similar?

How can I make sure I am attempting to this correctly?

Could it be on a different frequency than the default 912.60 MHz?

I'm new to SDR but I'm using SDRSharp and I can't find any signals except for maybe Z-Wave but I'm really not sure.

**Comment by bemasher** [comment]
Have a look at #105.
