### ISSUE TITLE
Is it possible to support G5R1s?

### ISSUE THREAD

**Issue by JeffreyFalgout** [bemasher/rtlamr#277]
My energy provider decided to swap out my meter today, replacing my C1A3B Itron with a G5R1 Itron. I don't see it when I spin up a broad listener, and it looks like G5R1 uses both 900 MHz and 2.4 GHz (https://fcc.report/FCC-ID/SK9G5R1/4887672.pdf) which makes me think it might not be possible to support it with just an rtlsdr dongle :/

**Comment by bemasher** [comment]
See #284.
