### ISSUE TITLE
All fcc.io device links return "Internal Server Error - Read"

### ISSUE THREAD

**Issue by PalantirWielder** [bemasher/rtlamr#281]
https://github.com/bemasher/rtlamr/blob/7926ab759fcd07021dfa37d115db4fd10f2d127c/meters.csv#L9

Not sure if it's a temporary outage, or if something is permanently broken.

Changing fcc.io to fccid.io appears to work, however.

**Comment by bemasher** [comment]
Looks like this was a transient issue. I'll update all the links to https scheme though.

**Comment by bemasher** [comment]
Closed in dcdddc5.
