### ISSUE TITLE
CSV output is garbled

### ISSUE THREAD

**Issue by tastyratz** [bemasher/rtlamr#32]
Windows bin precompiled run from the command line as shown:
rtlamr -format=csv -samplefile=output.csv

csv is 70kb with only 2 readings

Example paste of the output:
€€ƒ€€„{}€~{€€~|€‚ƒ‡{€{€€‚{}{€}{‚}ƒ€‚~}€~‚~}}}†€…~y‚}‰…}~{ƒ€z‚‚‚}‡~|y„x€x€

Let me know if any other details are needed.

**Comment by bemasher** [comment]
The data written to `output.csv` in your example are raw samples from the dongle whenever a message is successfully decoded. In order to get csv output written to `output.csv` you'll want to use the `-logfile` flag:

    rtlamr -format=csv -logfile=output.csv
