### ISSUE TITLE
1.4GHz water meters

### ISSUE THREAD

**Issue by jdleslie** [bemasher/rtlamr#45]
Any ability to receive data from an Itron 200WM (1.4GHz) meter by changing center frequency?

IC ID: 864D-1430WA
Bands: 1427-1430 MHz, 1493.5-1496.5 MHz

**Comment by bemasher** [comment]
From what little information I can find about the meter, it appears to be FM modulated and part of a fixed network which means it likely only transmits when queried by the utility. Support for these meters is unplanned at this point.
