### ISSUE TITLE
Capturing ERT packet for peak 15 min. load?

### ISSUE THREAD

**Issue by hansthompson** [bemasher/rtlamr#56]
In my area, the meters are broadcast a 15 minute peak load in addition to a SCM message of cumulative consumption.   

Is there a specific message type that would broadcast this 15 minute load? If it is coming off the same Intron meter for the electrical SCM message is it broadcasting in SCM as well?

**Comment by bemasher** [comment]
What documentation do you have that supports this? The only other kind of message I'm aware of that power meters might transmit are IDM messages which include differential interval data at 5 minutes per interval.

**Comment by hansthompson** [comment]
This is what I've heard from the director of IT from my local utility.  I'll check the IDM message.
