### ISSUE TITLE
Lost quiet option

### ISSUE THREAD

**Issue by val123456** [bemasher/rtlamr#71]
Version I have on an older system supports this option:

-quiet=false: suppress printing state information at startup

Version I pulled and built today does not.  What happened?  It was a useful option!

By the way, great program!

Thanks,

val

**Comment by bemasher** [comment]
The `-quiet` flag was deprecated when the log output flags were removed. Receiver state is logged to stderr on startup, so if you're using redirection to pipe stdout to a file or another program, it shouldn't interfere with anything. If you need to suppress it:

On windows:
```
rtlamr 2>NUL
```

On Unix/Linux:
```
rtlamr 2>/dev/null
```

You can direct stdout to a file at the same time if you need:
```
rtlamr 2>/dev/null > output.log
```
