### ISSUE TITLE
Could this work for 467 MHz signal?

### ISSUE THREAD

**Issue by poldim** [bemasher/rtlamr#72]
I'm a total newb to this but I'd love to figure out how to do this for my water meter. My utility uses an ALCARA water meter (http://www.sfwater.org/modules/showdocument.aspx?documentid=12). Looks like it uses a 467 MHz receiver antenna to pick up signals.

This (http://69.128.42.202/Usage%20Reports/All/Homesteader.html) looked like a small utility pulling in their data but probably using Aclaras hardware to do so. 

I see there RTL2832U tunes from 500 kHz to 1.7 GTX.  Does that mean this won't work?  Or is there something else I can use other than the RTL2832U that covers the 467 MHz range?

Any help is appreciated.

**Comment by bemasher** [comment]
Most rtl-sdr dongles are capable of receiving signals anywhere between 40 MHz and 1.7 GHz, your meter is transmitting at 467 MHz which falls within that range. However, the modulation and protocol are not supported in rtlamr.
