### ISSUE TITLE
Other SDRs?

### ISSUE THREAD

**Issue by mntnmn** [bemasher/rtlamr#78]
What would it take to port this app to other SDRs. I am interested in LimeSDR specifically but generally I want to know exactly what the app needs from the SDR. Active control of frequency? Bandwidth? Gain? Sample rate? All of this is possible on other SDRs. If I set settings separately on another program and open a TCP port will rtlamr work that way?
Wow! You are there! That was fast. I hit the wrong button....
(Or maybe that was a robot?)

**Comment by bemasher** [comment]
Please provide some more information about what you're looking for here.

**Comment by ImDroided** [comment]
Hackrf would be awesome. I can then possibly pick up my meters in the 2.4ghz range

**Comment by bemasher** [comment]
That is unlikely, I don't know of any ERT compatible meters (for any commodity) that operate outside of the 915 MHz ISM band.

HackRF support would likely take the form of a spectrum server compatible with the rtl_tcp protocol for the HackRF. I'll consider it.

**Comment by mntnmn** [comment]
I have looked through the code and find it tightly bound to a lot of RTL specific calls in a lot of different places. This makes me believe that an RTL simulator is the only way to do it without a major re-write.
SDRAngel can open a TCP or UDP port feeding raw I/Q or demod at any device supported bandwidth and sample rate. This was my angle on getting a pipeline to rtlamr.

**Comment by ImDroided** [comment]
I have one from these guys and I guess in my area they are on 2.4 at least I cant get anything in the 900 range.

https://www.comed.com/SiteCollectionDocuments/SmartEnergy/RadioFrequencyQA.PDF

**Comment by bemasher** [comment]
An rtl_tcp flavored implementation for hackrf would be fairly trivial as I've already written a package for interfacing with a hackrf, however, it will not be easily portable between linux and windows.

**Comment by bluegizmo83** [comment]
Any update on this being made compatible with the HackRF on Windows?

**Comment by bemasher** [comment]
Have not had time or motivation to work on a port for this given that rtl-sdr dongles are so cheap and readily available.

**Comment by amm3** [comment]
> An rtl_tcp flavored implementation for hackrf would be fairly trivial as I've already written a package for interfacing with a hackrf, however, it will not be easily portable between linux and windows.

FWIW, there is hackrf implementation of rtl_tcp available in this fork of main hackrf codebase: #https://github.com/avian2/hackrf 
Unfortunately I haven't been able to get it to work with rtlamr thus far.
