### ISSUE TITLE
sync.Pool requires go 1.3

### ISSUE THREAD

**Issue by SergeiDelov** [bemasher/rtlamr#80]
Error: rtlamr/main.go:127: undefined: sync.Pool

see: https://golang.org/doc/go1.3
So,  either docs or code should be changed. Currently doc states "### Requirements * GoLang >=1.2"

Regards,
Serge

**Comment by bemasher** [comment]
Yep, you caught it before I did. Travis-CI failed last night after this build but I didn't check it until today when you opened this issue. The version requirement has been bumped to >= 1.3. The userbase still on 1.2 is likely to be very small.

Fixed by f8b5ccb4b72df57fbae235ba98552470c5eef807
