### ISSUE TITLE
Output valid JSON

### ISSUE THREAD

**Issue by jlmcgraw** [bemasher/rtlamr#85]
Current JSON output isn't strictly valid, it is missing double quotes and commas

eg:

```json
{Time:2017-12-30T18:06:13.834 SCM:{ID:28439446 Type:13 Tamper:{Phy:01 Enc:00} Consumption:   79855 CRC:0x4F4F}}
```

should be:

```json
{"Time": "2017 - 12 - 30 T18: 06: 13.834", "SCM": {"ID": "28439446","Type": "13", "Tamper": {"Phy": "01", "Enc": "00"},"Consumption": "79855","CRC": "0x4F4F"}}
```

**Comment by bemasher** [comment]
What value was passed to `-format` for the first output example?

**Comment by jlmcgraw** [comment]
Sheesh.  Mea culpa. 

-format=json works properly  when you enable it properly  :)

**Comment by bemasher** [comment]
For clarification to others encountering this, default output format is go's `%+v` Printf verb, which is vaguely json-like.
