### ISSUE TITLE
Error connecting to spectrum server

### ISSUE THREAD

**Issue by eightysteele** [bemasher/rtlamr#88]
Hello! 

I installed `rtlamr` via `go get github.com/bemasher/rtlamr` with Go version `go1.9.2 darwin/amd64` on OS X version `10.11.6 (15G1004)`, but I'm getting an error about connecting to spectrum server.

To reproduce, I'm testing with `rtlamr -msgtype=idm --format=json -msgtype=scm+` which fails with:

```bash
main.go:59: Error connecting to spectrum server: dial tcp 127.0.0.1:1234: getsockopt: connection refused
```

Looks like maaaaybe github.com/bemasher/rtltcp wasn't installed correctly? I can't run `rtl_tcp` and it doesn't appear to be anywhere on my machine.

Thanks for any help!

**Comment by toastedcornflakes** [comment]
rtl_tcp is from the RTL-SDR software distribution. You can install it by following [those instructions](https://gist.github.com/jheasly/9477732).

**Comment by bemasher** [comment]
Due to a somewhat unfortunate naming scheme the `github.com/bemasher/rtl-tcp` golang package is often confused with the spectrum server `rtl_tcp`. Please note that the golang package only allows rtlamr to speak to the spectrum server, you are responsible for obtaining binaries or building the spectrum server from source.

**Comment by bemasher** [comment]
I should also note that the example invocation you gave is not going to do what you think it will do. rtlamr does not support multiple protocols per instance and providing more than one `msgtype` flag will use the value given in the last instance of the flag. Your example will only listen for SCM+ packets, not IDM and SCM+.
