### ISSUE TITLE
R900 Working? 

### ISSUE THREAD

**Issue by JacobAltar** [bemasher/rtlamr#94]
rtlamr readings are not matching the display of the r900. I don't believe it is a simple hex2dec or unit conversion. For example, the display read 469706 while rtlamr reports 13564690. But what's promising is that the consumption number does increase.

**Comment by bemasher** [comment]
Have you tried the r900bcd msgtype? This was previously encountered and a msgtype that performs binary coded digit translation on the consumption value, it is otherwise identical to the r900 protocol.

**Comment by bemasher** [comment]
Closing due to age.
