### ISSUE TITLE
Ubuntu 16.04 LTS RTL-SDR Package Build Error

### ISSUE THREAD

**Issue by MaxFun** [bemasher/rtlamr#95]
Downloaded RTL_SDR ( git clone git://git.osmocom.org/rtl-sdr.git) 
Then ran 
root@shorty-Vostro1310:/root/rtl-sdr/build# cmake ../
-- Build type not specified: defaulting to release.
-- Extracting version information from git describe...
-- Checking for module 'libusb-1.0'
--   No package 'libusb-1.0' found
-- libusb-1.0 not found.
 CMake Error at CMakeLists.txt:72 (message):
  LibUSB 1.0 required to compile rtl-sdr
-- Configuring incomplete, errors occurred!
See also "/root/rtl-sdr/build/CMakeFiles/CMakeOutput.log".
See also "/root/rtl-sdr/build/CMakeFiles/CMakeError.log".

and got error "No package 'libusb-1.0' found"

To check for 'libusb-1.0', I ran 

root@shorty-Vostro1310:/root/rtl-sdr/build# apt-cache search libusb-1.0
libusb-1.0-0 - userspace USB programming library
libusb-1.0-0-dbg - userspace USB programming library development files
libusb-1.0-0-dev - userspace USB programming library development files
libusb-1.0-doc - documentation for userspace USB programming
libusb-ocaml - OCaml bindings to libusb-1.0 (runtime)
libusb-ocaml-dev - OCaml bindings to libusb-1.0
lm4flash - Command-line firmware flashing tool to communicate with the Stellaris Launchpad
python-usb - USB interface for Python
python3-usb - USB interface for Python (Python3)

which seem to indicate I have 'libusb-1.0' if I understand the output

Any suggestions ?

**Comment by bemasher** [comment]
I do not maintain and cannot provide support for rtl-sdr, you'll need to look into resources available from osmocom and ubuntu to solve your build issue.
