### ISSUE TITLE
LON protocol

### ISSUE THREAD

**Issue by fragolinux** [bemasher/rtlamr#96]
hi, i'm trying to check if i can read my gas and power meters, i leave in Italy, and scanning with every msgtype protocol you have in your software, it detects nothing here... i asked on an electronic group on facebook, someone suggested that our meters use the LON protocol, is it supported, or will be? Thanks
https://en.wikipedia.org/wiki/LonWorks

**Comment by bemasher** [comment]
It's not likely that support for the LON protocol will be added to rtlamr without some more specifics.

**Comment by fragolinux** [comment]
It's not even that, unfortunately... No wireless communication for us...
Ticket can be closed...

Il dom 6 mag 2018, 22:11 Douglas Hall <notifications@github.com> ha scritto:
